name: check
on:
  push:
  pull_request:
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: astral-sh/setup-uv@v3
      - run: python3 -m unittest discover
      - run: uvx ruff check
